name: moyu

# 定时触发触发
on:
  schedule:
    - cron: "00 01 * * *"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: run
        run: |
          pip install requests
          python3 摸鱼.py
          git config --global user.email "fangweilong@outlook.com"
          git config --global user.name "Teler"
          git commit -m "提交摸鱼语录更新" -a
      - name: push-action
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: main
