name: moyu

# 定时触发触发
on:
  push:
    schedule:
      - cron: 8 * * * *

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: run
        run: |
          python3 摸鱼.py
      - uses: actions-go/push@master
        with:
          commit-message: '自动提交'
          remote: origin