name: moyu

# 定时触发触发
on:
  push:
  schedule:
    - cron: 10 * * * *

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: run
        run: |
          pip install requests
          python3 摸鱼.py
      - name: push-action
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: master